export const PLACE_STATUS = {
  ALL: 'all',
  BACKLOG: 'backlog',
  DONE: 'done',
};

export const VIEW_TYPE = {
  LIST: 'list',
  MAP: 'map',
};

export const SIDO = [
  {name_en: 'All', name_kr: '전체(시/도)'},
  {name_en: 'Seoul', name_kr: '서울특별시'},
  {name_en: 'Busan', name_kr: '부산광역시'},
  {name_en: 'Daegu', name_kr: '대구광역시'},
  {name_en: 'Incheon', name_kr: '인천광역시'},
  {name_en: 'Gwangju', name_kr: '광주광역시'},
  {name_en: 'Daejeon', name_kr: '대전광역시'},
  {name_en: 'Ulsan', name_kr: '울산광역시'},
  {name_en: 'Sejong', name_kr: '세종특별자치시'},
  {name_en: 'Gyeonggido', name_kr: '경기도'},
  {name_en: 'Gangwondo', name_kr: '강원도'},
  {name_en: 'Chungcheongbukdo', name_kr: '충청북도'},
  {name_en: 'Chungcheongnamdo', name_kr: '충청남도'},
  {name_en: 'Jeollabukdo', name_kr: '전라북도'},
  {name_en: 'Jeollanamdo', name_kr: '전라남도'},
  {name_en: 'Gyeongsangbukdo', name_kr: '경상북도'},
  {name_en: 'Gyeongsangnamdo', name_kr: '경상남도'},
  {name_en: 'Jejudo', name_kr: '제주특별자치도'},
];

export const SIGUNGU = {
  seoul: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Gangnam', name_kr: '강남구'},
    {name_en: 'Gangdong', name_kr: '강동구'},
    {name_en: 'Gangbuk', name_kr: '강북구'},
    {name_en: 'Gangseo', name_kr: '강서구'},
    {name_en: 'Gwanak', name_kr: '관악구'},
    {name_en: 'Gwangjin', name_kr: '광진구'},
    {name_en: 'Gurogu', name_kr: '구로구'},
    {name_en: 'Geumcheon', name_kr: '금천구'},
    {name_en: 'Nowon', name_kr: '노원구'},
    {name_en: 'Dobong', name_kr: '도봉구'},
    {name_en: 'Dongdaemun', name_kr: '동대문구'},
    {name_en: 'Dongjak', name_kr: '동작구'},
    {name_en: 'Mapo', name_kr: '마포구'},
    {name_en: 'Seodaemun', name_kr: '서대문구'},
    {name_en: 'Seocho', name_kr: '서초구'},
    {name_en: 'Seongdong', name_kr: '성동구'},
    {name_en: 'Seongbuk', name_kr: '성북구'},
    {name_en: 'Songpa', name_kr: '송파구'},
    {name_en: 'Yangcheon', name_kr: '양천구'},
    {name_en: 'Yeongdeungpo', name_kr: '영등포구'},
    {name_en: 'Yongsan', name_kr: '용산구'},
    {name_en: 'Eunpyeong', name_kr: '은평구'},
    {name_en: 'Jongno', name_kr: '종로구'},
    {name_en: 'Jung', name_kr: '중구'},
    {name_en: 'Jungnang', name_kr: '중랑구'},
  ],
  busan: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Gangseo', name_kr: '강서구'},
    {name_en: 'Geumjeong', name_kr: '금정구'},
    {name_en: 'Gijang', name_kr: '기장군'},
    {name_en: 'Nam', name_kr: '남구'},
    {name_en: 'Dong', name_kr: '동구'},
    {name_en: 'Dongnae', name_kr: '동래구'},
    {name_en: 'Busanjin', name_kr: '부산진구'},
    {name_en: 'Buk', name_kr: '북구'},
    {name_en: 'Sasang', name_kr: '사상구'},
    {name_en: 'Saha', name_kr: '사하구'},
    {name_en: 'Seo', name_kr: '서구'},
    {name_en: 'Suyeong', name_kr: '수영구'},
    {name_en: 'Yeonje', name_kr: '연제구'},
    {name_en: 'Yeongdo', name_kr: '영도구'},
    {name_en: 'Jung', name_kr: '중구'},
    {name_en: 'Haeundae', name_kr: '해운대구'},
  ],
  daegu: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Nam', name_kr: '남구'},
    {name_en: 'Dalseo', name_kr: '달서구'},
    {name_en: 'Dalseong', name_kr: '달성군'},
    {name_en: 'Dong', name_kr: '동구'},
    {name_en: 'Buk', name_kr: '북구'},
    {name_en: 'Seo', name_kr: '서구'},
    {name_en: 'Suseong', name_kr: '수성구'},
    {name_en: 'Jung', name_kr: '중구'},
  ],
  incheon: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Ganghwa', name_kr: '강화군'},
    {name_en: 'Gyeyang', name_kr: '계양구'},
    {name_en: 'Namdong', name_kr: '남동구'},
    {name_en: 'Dong', name_kr: '동구'},
    {name_en: 'Michuhol', name_kr: '미추홀구'},
    {name_en: 'Bupyeong', name_kr: '부평구'},
    {name_en: 'Seo', name_kr: '서구'},
    {name_en: 'Yeonsu', name_kr: '연수구'},
    {name_en: 'Ongjin', name_kr: '옹진군'},
    {name_en: 'Jung', name_kr: '중구'},
  ],
  gwangju: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Gwangsan', name_kr: '광산구'},
    {name_en: 'Nam', name_kr: '남구'},
    {name_en: 'Dong', name_kr: '동구'},
    {name_en: 'Buk', name_kr: '북구'},
    {name_en: 'Seo', name_kr: '서구'},
  ],
  daejeon: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Daedeok', name_kr: '대덕구'},
    {name_en: 'Dong', name_kr: '동구'},
    {name_en: 'Seo', name_kr: '서구'},
    {name_en: 'Yuseong', name_kr: '유성구'},
    {name_en: 'Jung', name_kr: '중구'},
  ],
  ulsan: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Nam', name_kr: '남구'},
    {name_en: 'Dong', name_kr: '동구'},
    {name_en: 'Buk', name_kr: '북구'},
    {name_en: 'Ulju', name_kr: '울주군'},
    {name_en: 'Jung', name_kr: '중구'},
  ],
  sejong: [{name_en: 'All', name_kr: '전체(시/군/구)'}],
  gyeonggido: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Gapyeong', name_kr: '가평군'},
    {name_en: 'Deogyang', name_kr: '고양시 덕양구'},
    {name_en: 'Ilsandong', name_kr: '고양시 일산동구'},
    {name_en: 'Ilsanseo', name_kr: '고양시 일산서구'},
    {name_en: 'Gwacheon', name_kr: '과천시'},
    {name_en: 'Gwangmyeong', name_kr: '광명시'},
    {name_en: 'Gwangju', name_kr: '광주시'},
    {name_en: 'Guri', name_kr: '구리시'},
    {name_en: 'Gunpo', name_kr: '군포시'},
    {name_en: 'Gimpo', name_kr: '김포시'},
    {name_en: 'Namyangju', name_kr: '남양주시'},
    {name_en: 'Dongducheon', name_kr: '동두천시'},
    {name_en: 'Bucheon', name_kr: '부천시'},
    {name_en: 'Bundang', name_kr: '성남시 분당구'},
    {name_en: 'Sujeong', name_kr: '성남시 수정구'},
    {name_en: 'Jungwon', name_kr: '성남시 중원구'},
    {name_en: 'Gwonseon', name_kr: '수원시 권선구'},
    {name_en: 'Yeongtong', name_kr: '수원시 영통구'},
    {name_en: 'Jangan', name_kr: '수원시 장안구'},
    {name_en: 'Paldal', name_kr: '수원시 팔달구'},
    {name_en: 'Siheung', name_kr: '시흥시'},
    {name_en: 'Danwon', name_kr: '안산시 단원구'},
    {name_en: 'Sangnok', name_kr: '안산시 상록구'},
    {name_en: 'Anseong', name_kr: '안성시'},
    {name_en: 'Dongan', name_kr: '안양시 동안구'},
    {name_en: 'Manan', name_kr: '안양시 만안구'},
    {name_en: 'Yangju', name_kr: '양주시'},
    {name_en: 'Yangpyeong', name_kr: '양평군'},
    {name_en: 'Yeoju', name_kr: '여주시'},
    {name_en: 'Yeoncheon', name_kr: '연천군'},
    {name_en: 'Osan', name_kr: '오산시'},
    {name_en: 'Giheung', name_kr: '용인시 기흥구'},
    {name_en: 'Suji', name_kr: '용인시 수지구'},
    {name_en: 'Cheoin', name_kr: '용인시 처인구'},
    {name_en: 'Uiwang', name_kr: '의왕시'},
    {name_en: 'Uijeongbu', name_kr: '의정부시'},
    {name_en: 'Icheon', name_kr: '이천시'},
    {name_en: 'Paju', name_kr: '파주시'},
    {name_en: 'Pyeongtaek', name_kr: '평택시'},
    {name_en: 'Pocheon', name_kr: '포천시'},
    {name_en: 'Hanam', name_kr: '하남시'},
  ],
  gangwondo: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Gangneung', name_kr: '강릉시'},
    {name_en: 'Goseong', name_kr: '고성군'},
    {name_en: 'Donghae', name_kr: '동해시'},
    {name_en: 'Samcheok', name_kr: '삼척시'},
    {name_en: 'Sokcho', name_kr: '속초시'},
    {name_en: 'Yanggu', name_kr: '양구군'},
    {name_en: 'Yangyang', name_kr: '양양군'},
    {name_en: 'Yeongwol', name_kr: '영월군'},
    {name_en: 'Wonju', name_kr: '원주시'},
    {name_en: 'Inje', name_kr: '인제군'},
    {name_en: 'Jeongseon', name_kr: '정선군'},
    {name_en: 'Cheorwon', name_kr: '철원군'},
    {name_en: 'Chuncheon', name_kr: '춘천시'},
    {name_en: 'Taebaek', name_kr: '태백시'},
    {name_en: 'Pyeongchang', name_kr: '평창군'},
    {name_en: 'Hongcheon', name_kr: '홍천군'},
    {name_en: 'Hwacheon', name_kr: '화천군'},
    {name_en: 'Hoengseong', name_kr: '횡성군'},
  ],
  chungcheongbukdo: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Goesan', name_kr: '괴산군'},
    {name_en: 'Danyang', name_kr: '단양군'},
    {name_en: 'Boeun', name_kr: '보은군'},
    {name_en: 'Yeongdong', name_kr: '영동군'},
    {name_en: 'Okcheon', name_kr: '옥천군'},
    {name_en: 'Eumseong', name_kr: '음성군'},
    {name_en: 'Jecheon', name_kr: '제천시'},
    {name_en: 'Jeungpyeong', name_kr: '증평군'},
    {name_en: 'Jincheon', name_kr: '진천군'},
    {name_en: 'Sangdang', name_kr: '청주시 상당구'},
    {name_en: 'Seowon', name_kr: '청주시 서원구'},
    {name_en: 'Cheongwon', name_kr: '청주시 청원구'},
    {name_en: 'Heungdeok', name_kr: '청주시 흥덕구'},
    {name_en: 'Chungju', name_kr: '충주시'},
  ],
  chungcheongnamdo: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Gyeryong', name_kr: '계룡시'},
    {name_en: 'Gongju', name_kr: '공주시'},
    {name_en: 'Geumsan', name_kr: '금산군'},
    {name_en: 'Nonsan', name_kr: '논산시'},
    {name_en: 'Dangjin', name_kr: '당진시'},
    {name_en: 'Boryeong', name_kr: '보령시'},
    {name_en: 'Buyeo', name_kr: '부여군'},
    {name_en: 'Seosan', name_kr: '서산시'},
    {name_en: 'Seocheon', name_kr: '서천군'},
    {name_en: 'Asan', name_kr: '아산시'},
    {name_en: 'Yesan', name_kr: '예산군'},
    {name_en: 'Dongnam', name_kr: '천안시 동남구'},
    {name_en: 'Seobuk', name_kr: '천안시 서북구'},
    {name_en: 'Cheongyang', name_kr: '청양군'},
    {name_en: 'Taean', name_kr: '태안군'},
    {name_en: 'Hongseong', name_kr: '홍성군'},
  ],
  jeollabukdo: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Gochang', name_kr: '고창군'},
    {name_en: 'Gunsan', name_kr: '군산시'},
    {name_en: 'Gimje', name_kr: '김제시'},
    {name_en: 'Namwon', name_kr: '남원시'},
    {name_en: 'Muju', name_kr: '무주군'},
    {name_en: 'Buan', name_kr: '부안군'},
    {name_en: 'Sunchang', name_kr: '순창군'},
    {name_en: 'Wanju', name_kr: '완주군'},
    {name_en: 'Iksan', name_kr: '익산시'},
    {name_en: 'Imsil', name_kr: '임실군'},
    {name_en: 'Jangsu', name_kr: '장수군'},
    {name_en: 'Deokjin', name_kr: '전주시 덕진구'},
    {name_en: 'Wansan', name_kr: '전주시 완산구'},
    {name_en: 'Jeongeup', name_kr: '정읍시'},
    {name_en: 'Jinan', name_kr: '진안군'},
  ],
  jeollanamdo: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Gangjin', name_kr: '강진군'},
    {name_en: 'Goheung', name_kr: '고흥군'},
    {name_en: 'Gokseong', name_kr: '곡성군'},
    {name_en: 'Gwangyang', name_kr: '광양시'},
    {name_en: 'Gurye', name_kr: '구례군'},
    {name_en: 'Naju', name_kr: '나주시'},
    {name_en: 'Damyang', name_kr: '담양군'},
    {name_en: 'Mokpo', name_kr: '목포시'},
    {name_en: 'Muan', name_kr: '무안군'},
    {name_en: 'Boseong', name_kr: '보성군'},
    {name_en: 'Suncheon', name_kr: '순천시'},
    {name_en: 'Shinan', name_kr: '신안군'},
    {name_en: 'Yeosu', name_kr: '여수시'},
    {name_en: 'Yeonggwang', name_kr: '영광군'},
    {name_en: 'Yeongam', name_kr: '영암군'},
    {name_en: 'Wando', name_kr: '완도군'},
    {name_en: 'Jangseong', name_kr: '장성군'},
    {name_en: 'Jangheung', name_kr: '장흥군'},
    {name_en: 'Jindo', name_kr: '진도군'},
    {name_en: 'Hampyeong', name_kr: '함평군'},
    {name_en: 'Haenam', name_kr: '해남군'},
    {name_en: 'Hwasun', name_kr: '화순군'},
  ],
  gyeongsangbukdo: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Gyeongsan', name_kr: '경산시'},
    {name_en: 'Gyeongju', name_kr: '경주시'},
    {name_en: 'Goryeong', name_kr: '고령군'},
    {name_en: 'Gumi', name_kr: '구미시'},
    {name_en: 'Gunwi', name_kr: '군위군'},
    {name_en: 'Gimcheon', name_kr: '김천시'},
    {name_en: 'Mungyeong', name_kr: '문경시'},
    {name_en: 'Bonghwa', name_kr: '봉화군'},
    {name_en: 'Sangju', name_kr: '상주시'},
    {name_en: 'Seongju', name_kr: '성주군'},
    {name_en: 'Andong', name_kr: '안동시'},
    {name_en: 'Yeongdeok', name_kr: '영덕군'},
    {name_en: 'Yeongyang', name_kr: '영양군'},
    {name_en: 'Yeongju', name_kr: '영주시'},
    {name_en: 'Yeongcheon', name_kr: '영천시'},
    {name_en: 'Yecheon', name_kr: '예천군'},
    {name_en: 'Ulleung', name_kr: '울릉군'},
    {name_en: 'Uljin', name_kr: '울진군'},
    {name_en: 'Uiseong', name_kr: '의성군'},
    {name_en: 'Cheongdo', name_kr: '청도군'},
    {name_en: 'Cheongsong', name_kr: '청송군'},
    {name_en: 'Chilgok', name_kr: '칠곡군'},
    {name_en: 'Nam', name_kr: '포항시 남구'},
    {name_en: 'Buk', name_kr: '포항시 북구'},
  ],
  gyeongsangnamdo: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Geoje', name_kr: '거제시'},
    {name_en: 'Geochang', name_kr: '거창군'},
    {name_en: 'Goseong', name_kr: '고성군'},
    {name_en: 'Gimhae', name_kr: '김해시'},
    {name_en: 'Namhae', name_kr: '남해군'},
    {name_en: 'Miryang', name_kr: '밀양시'},
    {name_en: 'Sacheon', name_kr: '사천시'},
    {name_en: 'Sancheong', name_kr: '산청군'},
    {name_en: 'Yangsan', name_kr: '양산시'},
    {name_en: 'Uiryeong', name_kr: '의령군'},
    {name_en: 'Jinju', name_kr: '진주시'},
    {name_en: 'Changnyeong', name_kr: '창녕군'},
    {name_en: 'Masanhappo', name_kr: '창원시 마산합포구'},
    {name_en: 'Masanhoewon', name_kr: '창원시 마산회원구'},
    {name_en: 'seongsan', name_kr: '창원시 성산구'},
    {name_en: 'Uichang', name_kr: '창원시 의창구'},
    {name_en: 'Jinhae', name_kr: '창원시 진해구'},
    {name_en: 'Tongyeong', name_kr: '통영시'},
    {name_en: 'Hadong', name_kr: '하동군'},
    {name_en: 'Haman', name_kr: '함안군'},
    {name_en: 'Hamyang', name_kr: '함양군'},
    {name_en: 'Hapcheon', name_kr: '합천군'},
  ],
  jejudo: [
    {name_en: 'All', name_kr: '전체(시/군/구)'},
    {name_en: 'Seogwipo', name_kr: '서귀포시'},
    {name_en: 'Jeju', name_kr: '제주시'},
  ],
};
